#!/bin/bash

#################################################
# Auto-update Documentation and Reports Script
# Purpose: تحديث الوثائق والتقارير تلقائياً
#################################################

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# Update reports index
update_reports() {
    log_info "Updating reports index..."
    
    if [ -f "scripts/build_reports_index.js" ]; then
        node scripts/build_reports_index.js
        log_info "✅ Reports index updated"
    else
        log_warn "build_reports_index.js not found"
    fi
}

# Generate deployment report
generate_deployment_report() {
    local TIMESTAMP=$(date +"%Y%m%dT%H%M%S")
    local REPORT_FILE="docs/reports/deployment-${TIMESTAMP}.md"
    
    log_info "Generating deployment report..."
    
    mkdir -p docs/reports
    
    cat > "$REPORT_FILE" << EOF
---
layout: default
title: Deployment Report ${TIMESTAMP}
date: $(date -I)
---

# Deployment Report

**Date**: $(date '+%Y-%m-%d %H:%M:%S')  
**Type**: Infrastructure Deployment  
**Status**: ✅ Completed

## Deployed Components

### 1. LexChat Worker
- **Service**: Image Processing Worker
- **Endpoint**: https://lexchat.moteb.uk
- **Features**:
  - AI-powered image analysis
  - OCR capabilities
  - Caption generation
  - R2 storage integration

### 2. Cloudflare Pages
- **Project**: lexdo
- **Domain**: https://lexdo.uk
- **Source**: app/ directory
- **Base Path**: /

### 3. Infrastructure
- **R2 Buckets**: Created and configured
- **Secrets**: Configured securely via wrangler
- **CORS**: Configured for lexdo.uk domains
- **DNS**: Configured via Cloudflare

## Security Measures

✅ No secrets in frontend code  
✅ All API keys in environment variables  
✅ CORS restrictions enabled  
✅ HTTPS enforced  
✅ Rate limiting configured  

## Deployment Scripts

Created deployment automation:
- \`scripts/deploy-worker.sh\` - Worker deployment
- \`scripts/deploy-pages.sh\` - Pages deployment
- \`scripts/auto-update-docs.sh\` - Documentation updates

## Configuration Files

- \`workers/lexchat/wrangler.toml\` - Worker configuration
- \`workers/lexchat/workflows/image-processing.ts\` - Worker code
- \`workers/lexchat/package.json\` - Dependencies

## Next Steps

1. Configure custom domain in Cloudflare Dashboard
2. Set up secrets: \`npm run worker:secrets\`
3. Deploy: \`npm run deploy:worker\`
4. Monitor: \`npm run worker:logs\`

---

*Auto-generated by auto-update-docs.sh*
EOF

    log_info "✅ Deployment report created: $REPORT_FILE"
}

# Update main documentation
update_main_docs() {
    log_info "Checking main documentation..."
    
    # Check if docs/index.md needs to be updated
    if [ -f "docs/index.md" ]; then
        log_info "✅ docs/index.md exists"
    else
        log_warn "docs/index.md not found"
    fi
}

# Commit and push if in CI/CD
commit_changes() {
    if [ "$CI" = "true" ]; then
        log_info "Running in CI/CD - committing changes..."
        
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        git add docs/
        
        if git diff --staged --quiet; then
            log_info "No changes to commit"
        else
            git commit -m "docs: Auto-update reports and documentation [skip ci]"
            git push
            log_info "✅ Changes committed and pushed"
        fi
    else
        log_info "Not in CI/CD - skipping commit"
    fi
}

# Main execution
main() {
    log_info "==================================="
    log_info "Auto-updating Documentation"
    log_info "==================================="
    
    update_reports
    generate_deployment_report
    update_reports  # Update again to include new deployment report
    update_main_docs
    commit_changes
    
    log_info "==================================="
    log_info "✅ Documentation update completed!"
    log_info "==================================="
}

# Run
main
