#!/bin/bash
# BSM PR Merge Automation Script
# Generated by: BSM Autonomous Architect
# Date: 2026-02-07

set -e

REPO="LexBANK/BSM"
PLAN_FILE="reports/pr-merge-plan.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command -v gh &> /dev/null; then
        log_error "GitHub CLI (gh) not found. Install: https://cli.github.com/"
        exit 1
    fi
    
    if ! command -v jq &> /dev/null; then
        log_error "jq not found. Install: apt-get install jq"
        exit 1
    fi
    
    # Check if authenticated
    if ! gh auth status &> /dev/null; then
        log_error "Not authenticated with GitHub CLI. Run: gh auth login"
        exit 1
    fi
    
    log_success "Prerequisites check passed"
}

# Phase 1: Cleanup Meta PRs
phase_1_cleanup() {
    log_info "=== PHASE 1: Immediate Cleanup ==="
    
    local meta_prs=(78 76 75)
    
    for pr in "${meta_prs[@]}"; do
        log_warning "Closing meta PR #$pr..."
        
        # Create issue to track the content
        log_info "Creating tracking issue for PR #$pr..."
        gh issue create \
            --repo "$REPO" \
            --title "[Archived] Content from PR #$pr" \
            --body "This issue tracks the analysis from closed PR #$pr. See the PR for details." \
            --label "archived,meta" || true
        
        # Close the PR with comment
        gh pr close "$pr" \
            --repo "$REPO" \
            --comment "Closing meta/analysis PR as per merge consolidation plan. Content archived in related issue." || true
        
        log_success "Closed PR #$pr"
    done
    
    log_success "Phase 1 completed"
}

# Phase 2: Critical Foundation
phase_2_foundation() {
    log_info "=== PHASE 2: Critical Foundation ==="
    
    # 2.1 Merge documentation
    log_info "Merging PR #77 (CLAUDE.md documentation)..."
    gh pr merge 77 \
        --repo "$REPO" \
        --squash \
        --delete-branch \
        --body "Essential project documentation" || {
        log_warning "PR #77 merge failed or already merged"
    }
    
    # 2.2 Security audit preparation
    log_warning "PR #58 (Security Audit) requires manual review"
    log_info "Actions needed:"
    echo "  1. Review security findings in PR #58"
    echo "  2. Apply GitHub Actions pinning"
    echo "  3. Upgrade CodeQL v2 to v3"
    echo "  4. Test security workflows"
    echo "  5. Run: gh pr merge 58 --repo $REPO --squash"
    
    # 2.3 Performance improvements
    log_warning "PR #69 (Performance) requires testing"
    log_info "Actions needed:"
    echo "  1. Run performance benchmarks"
    echo "  2. Verify no breaking changes"
    echo "  3. Load testing"
    echo "  4. Run: gh pr merge 69 --repo $REPO --squash"
    
    log_success "Phase 2 initiated (manual steps required)"
}

# Phase 3: CI/CD Consolidation
phase_3_cicd() {
    log_info "=== PHASE 3: CI/CD Consolidation ==="
    
    local cicd_prs=(61 62 74 68)
    local feature_branch="feature/unified-cicd"
    
    log_info "Creating consolidated feature branch: $feature_branch"
    
    git checkout main
    git pull origin main
    git checkout -b "$feature_branch" || git checkout "$feature_branch"
    
    log_info "Manual consolidation required:"
    echo "  PRs to consolidate: ${cicd_prs[*]}"
    echo "  1. Review each PR's workflow files"
    echo "  2. Cherry-pick best practices from each"
    echo "  3. Remove duplicates"
    echo "  4. Test all workflows"
    echo "  5. Create consolidated PR from $feature_branch"
    echo "  6. Close source PRs after merge"
    
    log_success "Phase 3 branch created (manual work required)"
}

# Phase 4: AgentOS & ORBIT
phase_4_features() {
    log_info "=== PHASE 4: Major Features ==="
    
    # AgentOS consolidation
    log_info "AgentOS consolidation strategy:"
    echo "  PRs: 50, 52, 53, 46, 47, 49"
    echo "  Strategy: Progressive integration"
    echo "  Target: feature/agentos-unified"
    echo ""
    echo "  Version plan:"
    echo "    v1.0: Core Engine (PR #50)"
    echo "    v1.1: Dashboard APIs (PR #53)"
    echo "    v1.2: Multi-provider (PRs #49, #47)"
    
    # ORBIT consolidation
    log_info "ORBIT consolidation strategy:"
    echo "  PRs: 63, 64, 66, 70"
    echo "  Strategy: Unified self-healing"
    echo "  Target: feature/orbit-unified"
    
    log_warning "Phase 4 requires architectural decisions and extensive work"
}

# Generate status report
generate_report() {
    log_info "Generating status report..."
    
    local report_file="reports/pr-merge-status-$(date +%Y%m%d).md"
    
    cat > "$report_file" << EOF
# PR Merge Execution Status
**Date:** $(date +%Y-%m-%d)
**Repository:** $REPO

## Phase Status

### Phase 1: Cleanup ✅
- Meta PRs closed: #78, #76, #75
- Tracking issues created

### Phase 2: Foundation 🔄
- [ ] PR #77: Documentation
- [ ] PR #58: Security Audit (manual review)
- [ ] PR #69: Performance (testing required)

### Phase 3: CI/CD 📋
- [ ] Feature branch created
- [ ] Consolidation in progress
- Target: $(jq -r '.estimated_timeline.phase_3' "$PLAN_FILE")

### Phase 4: Features 📋
- [ ] AgentOS strategy defined
- [ ] ORBIT strategy defined
- Target: $(jq -r '.estimated_timeline.phase_4' "$PLAN_FILE")

## Next Steps
1. Complete manual review of security PR #58
2. Run performance tests for PR #69
3. Begin CI/CD consolidation
4. Schedule AgentOS architecture meeting

## Metrics
- Total PRs: 55
- Target PRs: <15
- Completion: $(date +%Y-%m-%d)

---
*Generated by: scripts/execute-pr-merge-plan.sh*
EOF

    log_success "Report saved: $report_file"
    cat "$report_file"
}

# Main execution
main() {
    echo "╔══════════════════════════════════════════════╗"
    echo "║  BSM PR Merge Plan Execution                ║"
    echo "║  Repository: $REPO              ║"
    echo "╚══════════════════════════════════════════════╝"
    echo ""
    
    check_prerequisites
    
    log_warning "This script will modify repository state!"
    read -p "Continue? (yes/no): " confirm
    
    if [[ "$confirm" != "yes" ]]; then
        log_error "Execution cancelled by user"
        exit 0
    fi
    
    # Execute phases
    phase_1_cleanup
    echo ""
    
    phase_2_foundation
    echo ""
    
    log_info "Phases 3 and 4 require manual execution"
    log_info "Use: ./scripts/execute-pr-merge-plan.sh phase3"
    log_info "     ./scripts/execute-pr-merge-plan.sh phase4"
    echo ""
    
    generate_report
    
    log_success "╔══════════════════════════════════════════════╗"
    log_success "║  Execution completed!                        ║"
    log_success "╚══════════════════════════════════════════════╝"
}

# Allow running specific phases
if [[ $# -gt 0 ]]; then
    case "$1" in
        phase1)
            check_prerequisites
            phase_1_cleanup
            ;;
        phase2)
            check_prerequisites
            phase_2_foundation
            ;;
        phase3)
            check_prerequisites
            phase_3_cicd
            ;;
        phase4)
            check_prerequisites
            phase_4_features
            ;;
        report)
            generate_report
            ;;
        *)
            log_error "Unknown phase: $1"
            echo "Usage: $0 [phase1|phase2|phase3|phase4|report]"
            exit 1
            ;;
    esac
else
    main
fi
