#!/usr/bin/env bash
# ===========================================================================
# BSM Runner - Go Build and Test Script
# ===========================================================================
# Purpose: Execute Go build and test commands, collect results and logs
# Usage: ./scripts/run-go-example.sh [OUTPUT_DIR]
# ===========================================================================

set -euo pipefail

OUTPUT_DIR="${1:-reports}"
TIMESTAMP="$(date +"%Y%m%dT%H%M%S")"
RESULT_FILE="${OUTPUT_DIR}/go-result-${TIMESTAMP}.json"
MD_REPORT="${OUTPUT_DIR}/go-report-${TIMESTAMP}.md"

mkdir -p "${OUTPUT_DIR}"

# ---------------------------------------------------------------------------
# Initialize result structure
# ---------------------------------------------------------------------------
cat > "${RESULT_FILE}" <<EOF
{
  "timestamp": "${TIMESTAMP}",
  "language": "go",
  "project": "examples/go-example",
  "steps": []
}
EOF

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
log_step() {
  local step_name="$1"
  local status="$2"
  local output="$3"
  
  # Append step to JSON (simple append, not proper JSON merging)
  echo "  Step: ${step_name} - ${status}"
}

# ---------------------------------------------------------------------------
# Step 1: Go Version Check
# ---------------------------------------------------------------------------
echo "=== Checking Go Version ==="
GO_VERSION=$(go version)
echo "${GO_VERSION}"
log_step "go_version" "success" "${GO_VERSION}"

# ---------------------------------------------------------------------------
# Step 2: Go Build
# ---------------------------------------------------------------------------
echo ""
echo "=== Building Go Application ==="
cd examples/go-example

if go build -o app main.go; then
  echo "✓ Build successful"
  BUILD_STATUS="success"
  BUILD_OUTPUT="Build completed successfully"
else
  echo "✗ Build failed"
  BUILD_STATUS="failed"
  BUILD_OUTPUT="Build failed"
fi
log_step "go_build" "${BUILD_STATUS}" "${BUILD_OUTPUT}"

# ---------------------------------------------------------------------------
# Step 3: Run Application
# ---------------------------------------------------------------------------
echo ""
echo "=== Running Go Application ==="
if [ "${BUILD_STATUS}" = "success" ]; then
  RUN_OUTPUT=$(./app 2>&1)
  echo "${RUN_OUTPUT}"
  log_step "go_run" "success" "${RUN_OUTPUT}"
else
  echo "Skipped (build failed)"
  log_step "go_run" "skipped" "Build failed"
fi

# ---------------------------------------------------------------------------
# Step 4: Run Tests
# ---------------------------------------------------------------------------
echo ""
echo "=== Running Go Tests ==="
if go test -v 2>&1 | tee /tmp/go-test-output.txt; then
  TEST_STATUS="success"
  TEST_OUTPUT=$(cat /tmp/go-test-output.txt)
  echo "✓ All tests passed"
else
  TEST_STATUS="failed"
  TEST_OUTPUT=$(cat /tmp/go-test-output.txt)
  echo "✗ Tests failed"
fi
log_step "go_test" "${TEST_STATUS}" "${TEST_OUTPUT}"

# ---------------------------------------------------------------------------
# Generate Markdown Report
# ---------------------------------------------------------------------------
cd ../..

cat > "${MD_REPORT}" <<MDEOF
# BSM Runner - Go Build Report

**Timestamp:** ${TIMESTAMP}  
**Project:** examples/go-example  
**Language:** Go

## Summary

| Step | Status |
|------|--------|
| Go Version | ✓ Success |
| Build | $([ "${BUILD_STATUS}" = "success" ] && echo "✓ Success" || echo "✗ Failed") |
| Run | $([ "${BUILD_STATUS}" = "success" ] && echo "✓ Success" || echo "— Skipped") |
| Tests | $([ "${TEST_STATUS}" = "success" ] && echo "✓ Success" || echo "✗ Failed") |

## Details

### Go Version
\`\`\`
${GO_VERSION}
\`\`\`

### Build Output
\`\`\`
${BUILD_OUTPUT}
\`\`\`

### Application Output
\`\`\`
${RUN_OUTPUT:-N/A}
\`\`\`

### Test Results
\`\`\`
${TEST_OUTPUT}
\`\`\`

---
*Generated by BSM Runner Agent*
MDEOF

echo ""
echo "=== Report Generated ==="
echo "JSON: ${RESULT_FILE}"
echo "Markdown: ${MD_REPORT}"
echo ""
echo "=== Summary ==="
echo "Build: ${BUILD_STATUS}"
echo "Tests: ${TEST_STATUS}"

# Return appropriate exit code
if [ "${BUILD_STATUS}" = "success" ] && [ "${TEST_STATUS}" = "success" ]; then
  echo ""
  echo "✓ All checks passed"
  exit 0
else
  echo ""
  echo "✗ Some checks failed"
  exit 1
fi
