#!/usr/bin/env bash
set -euo pipefail

REPORT_DIR=${1:-reports}
OPEN_PR=${2:-false}
TIMESTAMP=$(date +"%Y%m%dT%H%M%S")
JSON_OUTFILE="${REPORT_DIR}/result_${TIMESTAMP}.json"
MARKDOWN_OUTFILE="${REPORT_DIR}/report_${TIMESTAMP}.md"
TMPDIR=$(mktemp -d)
ARCHITECT_RESULT="warning"
ARCHITECT_DETAILS="No architecture summary was generated"
RUNNER_RESULT="warning"
RUNNER_DETAILS="No npm tests were detected or npm was unavailable"
SECURITY_RESULT="warning"
SECURITY_DETAILS="Security scan completed with warnings"

mkdir -p "${REPORT_DIR}"

# Architect step (attempt Copilot CLI)
if command -v copilot >/dev/null 2>&1; then
  copilot agents run architect --repo . --output "${TMPDIR}/architect.json" || true
  if [ -f "${TMPDIR}/architect.json" ]; then
    ARCHITECT_RESULT="ok"
    ARCHITECT_DETAILS=$(jq -r '.summary // "Architecture summary generated"' "${TMPDIR}/architect.json" 2>/dev/null || echo "Architecture summary generated")
  else
    ARCHITECT_DETAILS="No architect JSON output; fallback quick scan performed"
  fi
else
  ARCHITECT_DETAILS="copilot CLI not found; fallback static analysis used"
fi

# Runner step
if [ -f package.json ] && command -v npm >/dev/null 2>&1; then
  if npm test --silent; then
    RUNNER_RESULT="ok"
    RUNNER_DETAILS="Tests passed"
  else
    RUNNER_RESULT="warning"
    RUNNER_DETAILS="Some tests failed; see CI logs"
  fi
else
  RUNNER_DETAILS="No npm tests detected or npm not installed"
fi

# Security step
if command -v snyk >/dev/null 2>&1; then
  snyk test --json > "${TMPDIR}/snyk.json" || true
  if [ -s "${TMPDIR}/snyk.json" ]; then
    SECURITY_RESULT="ok"
    SECURITY_DETAILS="Snyk results saved"
  else
    SECURITY_DETAILS="Snyk ran but returned no JSON output"
  fi
else
  SECURITY_DETAILS="Snyk not installed; skipping Snyk scan"
fi

SECRET_FOUND=false
if command -v git >/dev/null 2>&1; then
  while IFS= read -r f; do
    if grep -I -nE "AKIA|AIza|SECRET|PRIVATE_KEY|password|passwd|token|-----BEGIN PRIVATE KEY-----" "$f" >/dev/null 2>&1; then
      SECRET_FOUND=true
    fi
  done < <(git ls-files)
  if [ "$SECRET_FOUND" = true ]; then
    SECURITY_RESULT="warning"
    SECURITY_DETAILS="Potential secret patterns found during quick scan"
  elif [ "$SECURITY_RESULT" = "ok" ]; then
    SECURITY_DETAILS="Snyk results saved; no obvious secret patterns found"
  else
    SECURITY_DETAILS="Quick scan found no obvious secret patterns"
  fi
fi

OVERALL_STATUS="success"
for result in "$ARCHITECT_RESULT" "$RUNNER_RESULT" "$SECURITY_RESULT"; do
  if [ "$result" = "failed" ]; then
    OVERALL_STATUS="failed"
    break
  elif [ "$result" = "warning" ] && [ "$OVERALL_STATUS" = "success" ]; then
    OVERALL_STATUS="partial_success"
  fi
done

jq -n \
  --arg run_id "$TIMESTAMP" \
  --arg status "$OVERALL_STATUS" \
  --arg architect_result "$ARCHITECT_RESULT" \
  --arg architect_details "$ARCHITECT_DETAILS" \
  --arg runner_result "$RUNNER_RESULT" \
  --arg runner_details "$RUNNER_DETAILS" \
  --arg security_result "$SECURITY_RESULT" \
  --arg security_details "$SECURITY_DETAILS" \
  '{
    run_id: $run_id,
    status: $status,
    agents: [
      { name: "architect-agent", result: $architect_result, details: $architect_details },
      { name: "runner-agent", result: $runner_result, details: $runner_details },
      { name: "security-agent", result: $security_result, details: $security_details }
    ]
  }' > "$JSON_OUTFILE"

echo "▶ Converting JSON report to Markdown..."
node scripts/json_to_md.js "$JSON_OUTFILE" "$MARKDOWN_OUTFILE"

mkdir -p docs/reports
cp "$MARKDOWN_OUTFILE" "docs/reports/"
node scripts/build_reports_index.js

# Optional PR creation
PR_BRANCH="bsm-agents-suggestions-${TIMESTAMP}"
PR_TITLE="BSM Agents Suggestions - ${TIMESTAMP}"
PR_BODY_FILE="${TMPDIR}/pr-body.md"
cat > "${PR_BODY_FILE}" <<EOP
This PR contains suggested changes and recommendations generated by the BSM Agents run on ${TIMESTAMP}.

See the attached report in the repository or the workflow artifacts for details.
EOP

if [ "${OPEN_PR}" = "true" ]; then
  if command -v gh >/dev/null 2>&1; then
    git checkout -b "${PR_BRANCH}"
    mkdir -p .github/agents/reports
    cp "${MARKDOWN_OUTFILE}" ".github/agents/reports/report_${TIMESTAMP}.md"
    git add .github/agents/reports/report_${TIMESTAMP}.md
    git commit -m "Add agents report ${TIMESTAMP}" || true
    git push --set-upstream origin "${PR_BRANCH}"
    gh pr create --title "${PR_TITLE}" --body-file "${PR_BODY_FILE}" --label "automation" --draft
    echo "Draft PR created via gh CLI"
  else
    echo "gh CLI not found; cannot open PR automatically. Ensure gh is installed and logged in."
  fi
fi

echo "JSON report generated at ${JSON_OUTFILE}"
echo "Markdown report generated at ${MARKDOWN_OUTFILE}"
