#!/bin/bash
# DNS and Domain Setup Guide for BSM
# This script prints the required configuration steps.

echo "========================================"
echo "  BSM Domain Setup Guide"
echo "========================================"
echo ""
echo "1. Cloudflare DNS (lexprim.com & corehub.nexus)"
echo "   -----------------------------------------------"
echo "   A Records (GitHub Pages):"
echo "     @ -> 185.199.108.153"
echo "     @ -> 185.199.109.153"
echo "     @ -> 185.199.110.153"
echo "     @ -> 185.199.111.153"
echo ""
echo "   CNAME Record:"
echo "     www -> lexbank.github.io"
echo ""
echo "   Cloudflare Settings:"
echo "     - SSL/TLS: Full (strict)"
echo "     - Always Use HTTPS: ON"
echo "     - Auto Minify: HTML, CSS, JS"
echo ""
echo "2. GitHub Pages Setup"
echo "   -----------------------------------------------"
echo "   Repository: LexBANK/BSM"
echo "   Settings > Pages:"
echo "     - Source: GitHub Actions"
echo "     - Custom domain: www.lexprim.com"
echo "     - Enforce HTTPS: ON"
echo ""
echo "3. Render Backend (sr-bsm.onrender.com)"
echo "   -----------------------------------------------"
echo "   Environment Variables to set:"
echo "     CORS_ORIGINS=https://lexprim.com,https://corehub.nexus"
echo "     NODE_ENV=production"
echo ""
echo "4. GitHub Repository Secrets (for Telegram notifications)"
echo "   -----------------------------------------------"
echo "     TELEGRAM_BOT_TOKEN=<your-bot-token>"
echo "     TELEGRAM_CHAT_ID=<your-chat-id>"
echo ""
echo "5. Verify Setup"
echo "   -----------------------------------------------"
echo "   Test these URLs after configuration:"
echo "     https://lexprim.com/"
echo "     https://lexprim.com/kimi-chat.html"
echo "     https://corehub.nexus/"
echo "     https://sr-bsm.onrender.com/api/chat/direct"
echo ""
echo "========================================"
