id: bsm-agent-manifest
name: BSM Agent Manifest Standard
description: Canonical manifest contract used by BSM runtime to validate agent metadata.
category: system
version: "1.0.0"
owner: bsm-core
capabilities:
  - validation
  - routing
  - audit
contexts:
  chat: false
  api: true
  github: true
  ci: true
expose:
  selectable: false
  callable: true
  internal_only: true
triggers:
  manual: true
limits:
  max_tokens: 4096
  timeout_ms: 30000
audit:
  level: full
